### ISSUE TITLE
Is it dead code?

### ISSUE THREAD

**Issue by gladiko** [OHSystem/OHSystem#406]
Here is an example : 
```
     if (DPos!= string ::npos) {
            return s=m_LanRoomName[i].substr(DPos+l+2);
            ok = true; //never execute
            break; //never execute
     }
```
I notice code like that here and there. Is it some reason for this? I mean optimisations or bug fixing.

**Comment by Grief-Code** [comment]
In some way yes.
The code isnt written fully by me, we just made a bunch of extensions, and used some patches from here and there, probably some of the patches include such things and dead code.
Probably I wont handle the dead code, since its not that useful, it will be anyway ignored by the compiler.

**Comment by gladiko** [comment]
Okay, thanks for answer.
