### ISSUE TITLE
duplication games

### ISSUE THREAD

**Issue by Artyom91** [OHSystem/OHSystem#418]
https://hodovoi.ru/warcraft3/?u=6853

Castle Fight #19080
LTD x10 4k #17635
LTD x10 4k #17454
LTD x10 4k #17160
.....
...
...

?

**Comment by Artyom91** [comment]
I am use https://github.com/OHSystem/OHSystem/blob/v1.01/ghost_v1/update_stats/update_stats.cpp

How to watch the latest changes?

**Comment by Grief-Code** [comment]
The problem is, that git is saving histories from folders, and just files which were moved to a new folder cannot be tracked from the old directory.

The latest tracks before the reorganization of the repository can be found here:
https://github.com/OHSystem/OHSystem/commits/3ba628de46ecd452ef62d697e162bb80b135edd7/ghost%2B%2B/update_stats/update_stats.cpp

About the duplicated games, I do not think that this is an issue related to the stats updater. Are there 2 games saved to the database as well? Or is it only one game and displayed twice?

**Comment by Artyom91** [comment]
remove stats.

https://hodovoi.ru/warcraft3/?u=584 - new stats (two game).

**Comment by Artyom91** [comment]
@Grief-Code Hmm, in the database one game, the problem with the openstats?

**Comment by Artyom91** [comment]
Problem was solved.
The very problem appeared after cleaning statistics.
I forgot to clean the table: oh_w3mmdplayers, oh_w3mmdvars
